todoapp/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolistapp/',include('todolistapp.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

todolistapp/urls.py
from todolistapp import views
from django.urls import path

app_name = 'todolistapp'
urlpatterns = [
    path('',views.index,name='index'),
    # add items
    path('add', views.create_item, name='create_item'),
]

accounts/models.py
from django.db import models


# Create your models here.

todolistapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):

    task_username = models.CharField(max_length=200)
    task_title = models.CharField(max_length=200)
    task_desc = models.CharField(max_length=200)
    task_condition = models.IntegerField()
    task_assigned = models.IntegerField()

    def __str__(self):
        return self.task_title

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

todolistapp/forms.py
from  django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_username','task_title','task_desc','task_condition','task_assigned']

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('food:index')
    else:
        form = RegisterForm()
    return render(request,'users/register.html', {'form': form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

todolistapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from  .models import Task
from .forms import TaskForm

# Create your views here.
@login_required
def index(request):
        task_list = Task.objects.all()
        # template = loader.get_template('food/index.html')
        context = {
                'task_list': task_list
        }
        # return HttpResponse(template.render(context,request))
        return render(request, 'index.html', context)

@login_required
def create_item(request):
    form = TaskForm(request.POST or None)

    if form.is_valid():
        form.save()
        return  redirect('todolistapp:index')

    return render(request,'task-form.html',{'form': form})

accounts/templates/users/login.html
{% extends 'users/main.html' %}

{% block body %}
<div class="container mt-5">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Login</button>
        </form>
</div>

{% endblock %}

accounts/templates/users/logout.html
{% extends 'users/main.html' %}

{% block body %}
<div class="container">
    <h2>Your are Logout</h2>
</div>

{% endblock %}

accounts/templates/users/main.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Todo List App</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  mb-2 mb-lg-0  justify-content-end">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todolistapp:create_item' %}">Add Task</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="nav-link">Login</a>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


</body>
</html>

accounts/templates/users/profile.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Username: {{ user.username }}</h1>
</body>
</html>

accounts/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post">

    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>
</form>

</body>
</html>

todolistapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

todolistapp/templates/index.html
{% extends 'base.html' %}

{% block body %}

<!--Todo List Show-->
<div class="container">
    <h3>Show Task List</h3>
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
        </tr>
        </thead>
        <tbody>
        {% for task in task_list %}
        <tr>
            <th scope="row">1</th>
            <td>{{task.task_title}}</td>
            <td>Otto</td>
            <td>@mdo</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

todolistapp/templates/task-form.html
{% extends 'base.html' %}

{% block body %}
<form  method="POST">
     {%csrf_token%}
    {{form}}
    <button type="submit">Save</button>
</form>

{% endblock %}